config/routes.rb
# frozen_string_literal: true

resources :projects do
  resources :autolinks, only: %i[new edit create update destroy]
end

app/models/autolink.rb
# frozen_string_literal: true

class Autolink < ApplicationRecord
  belongs_to :project

  validates :prefix, presence: true, length: { in: 2..20 },
                     format: { with: /\A[A-Z_]+\z/ }
  validates :target_url, presence: true, length: { maximum: 255 },
                         format: { with: %r{\Ahttps?://.+<ref>.*\z} }

  class << self
    def for_issue(issue)
      where(project_id: issue.project_id).pluck(:prefix, :target_url).to_h
    end
  end
end

app/controllers/autolinks_controller.rb
# frozen_string_literal: true

class AutolinksController < ApplicationController
  before_action :authorize_global
  before_action :set_project
  before_action :set_autolink, only: %i[edit update destroy]

  def new
    @autolink = @project.autolinks.new
  end

  def edit; end

  def create
    @autolink = @project.autolinks.new(autolink_params)

    if @autolink.save
      redirect_to_settings
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @autolink.update(autolink_params)
      redirect_to_settings
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @autolink.destroy!
    redirect_to_settings
  end

  private

  def redirect_to_settings
    redirect_to settings_project_path(@project, tab: :autolinks)
  end

  def set_project
    @project = Project.find(params[:project_id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def set_autolink
    @autolink = @project.autolinks.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def autolink_params
    params.require(:autolink).permit(:prefix, :target_url)
  end
end

app/views/autolinks/_form.html.erb
<%= labelled_fields_for :autolink, @autolink do |f| %>
  <%= error_messages_for "autolink" %>
  <p><%= f.text_field :prefix, placeholder: t("autolinks_placeholder_prefix"),
                      maxlength: 20, required: true %></p>
  <p><%= t("autolinks_hint_prefix") %></p>
  <p><%= f.text_field :target_url, placeholder: t("autolinks_placeholder_target_url"),
                      size: 60, maxlength: 255, required: true %></p>
<% end %>

app/views/autolinks/edit.html.erb
<%= title t("autolinks_title_edit") %>

<%= labelled_form_for @autolink, url: project_autolink_path(@project, @autolink) do |f| %>
  <%= render partial: "autolinks/form", locals: { f: f } %>
  <%= submit_tag t("button_update") %>
<% end %>

app/views/autolinks/index.html.erb
<%= title t("autolinks_title_index") %>

<p><%= link_to t("autolinks_title_new"), new_project_autolink_path, class: "icon icon-add" %></p>

<% if @autolinks.any? %>
  <table class="list">
    <thead>
      <tr>
        <th><%= Autolink.human_attribute_name(:prefix) %></th>
        <th><%= Autolink.human_attribute_name(:target_url) %></th>
        <th style="width:15%"></th>
      </tr>
    </thead>
    <tbody>
      <% @autolinks.each do |autolink| %>
        <tr>
          <td class="name"><%= autolink.prefix %></td>
          <td class="name"><%= autolink.target_url %></td>
          <td class="buttons">
            <%= link_to t("button_edit"), edit_project_autolink_path(@project, autolink), class: "icon icon-edit" %>
            <%= delete_link project_autolink_path(@project, autolink) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p class="nodata"><%= t("label_no_data") %></p>
<% end %>

app/views/autolinks/new.html.erb
<%= title t("autolinks_title_new") %>

<%= labelled_form_for @autolink, url: project_autolinks_path(@project) do |f| %>
  <%= render partial: "autolinks/form", locals: { f: f } %>
  <%= submit_tag t("button_create") %>
<% end %>

app/views/projects/settings/_autolinks.html.erb
<% if User.current.allowed_to?(:manage_autolinks, @project) %>
  <p><%= link_to t("autolinks_title_new"), new_project_autolink_path(@project), class: "icon icon-add" %></p>
<% end %>

<% autolinks = @project.autolinks.to_a %>

<% if autolinks.any? %>
  <table class="list">
    <thead>
      <tr>
        <th><%= Autolink.human_attribute_name(:prefix) %></th>
        <th><%= Autolink.human_attribute_name(:target_url) %></th>
        <th style="width:15%"></th>
      </tr>
    </thead>
    <tbody>
      <% autolinks.each do |autolink| %>
        <tr>
          <td class="name"><%= autolink.prefix %></td>
          <td class="name"><%= autolink.target_url %></td>
          <td class="buttons">
            <% if User.current.allowed_to?(:manage_autolinks, @project) %>
              <%= link_to t("button_edit"), edit_project_autolink_path(@project, autolink), class: "icon icon-edit" %>
              <%= delete_link project_autolink_path(@project, autolink) %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p class="nodata"><%= t("label_no_data") %></p>
<% end %>